=== BackupTheBerlios/kttgs-svn/trunk/dtd/biketour.dtd
<!ELEMENT anecdote ( #PCDATA ) >
<!ATTLIST anecdote distance CDATA #REQUIRED >
<!ATTLIST anecdote image CDATA #REQUIRED >

<!ELEMENT crosspoint ( desc | images | profile-desc )* >
<!ATTLIST crosspoint direction NMTOKEN #REQUIRED >
<!ATTLIST crosspoint distance NMTOKEN #REQUIRED >
<!ATTLIST crosspoint elevation NMTOKEN #REQUIRED >
<!ATTLIST crosspoint latitude NMTOKEN #FIXED "000" >
<!ATTLIST crosspoint longitude NMTOKEN #FIXED "000" >

<!ELEMENT crosspoints ( crosspoint | track-info )* >

<!ELEMENT desc ( #PCDATA ) >

<!ELEMENT distance ( #PCDATA ) >
<!ATTLIST distance overwerite NMTOKEN #REQUIRED >
<!ATTLIST distance unit NMTOKEN #REQUIRED >

<!ELEMENT eatndrink ( #PCDATA ) >
<!ATTLIST eatndrink distance NMTOKEN #REQUIRED >
<!ATTLIST eatndrink image NMTOKEN #REQUIRED >
<!ATTLIST eatndrink type NMTOKEN #REQUIRED >

<!ELEMENT general ( name, distance, desc, reach, maps, roadmap, profile ) >
<!ATTLIST general duration NMTOKEN #REQUIRED >
<!ATTLIST general fitness-level NMTOKEN #REQUIRED >
<!ATTLIST general tech-level NMTOKEN #REQUIRED >
<!ATTLIST general type NMTOKEN #REQUIRED >

<!ELEMENT image EMPTY >
<!ATTLIST image name NMTOKEN #REQUIRED >

<!ELEMENT images ( image+ ) >

<!ELEMENT location EMPTY >
<!ATTLIST location city NMTOKEN #REQUIRED >
<!ATTLIST location country NMTOKEN #REQUIRED >
<!ATTLIST location region-or-state NMTOKEN #REQUIRED >
<!ATTLIST location zip-code NMTOKEN #REQUIRED >

<!ELEMENT map ( #PCDATA ) >

<!ELEMENT maps ( map ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT option ( #PCDATA ) >
<!ATTLIST option name CDATA #REQUIRED >

<!ELEMENT poi ( #PCDATA ) >
<!ATTLIST poi distance NMTOKEN #REQUIRED >
<!ATTLIST poi image NMTOKEN #REQUIRED >

<!ELEMENT profile EMPTY >

<!ELEMENT profile-desc ( #PCDATA ) >

<!ELEMENT reach ( option+ ) >

<!ELEMENT roadmap EMPTY >
<!ATTLIST roadmap image NMTOKEN #REQUIRED >

<!ELEMENT storage-info ( location ) >

<!ELEMENT tour-guide ( storage-info, general, crosspoints ) >

<!ELEMENT track-info ( anecdote | eatndrink | poi )* >
<!ATTLIST track-info pavement NMTOKEN #REQUIRED >

=== BackupTheBerlios/kttgs-svn/trunk/xml/skeleton-dtd-test.xml
<!DOCTYPE tour-guide SYSTEM "../dtd/biketour.dtd">

<tour-guide>

<storage-info>
   <location 
          country="de" 
          region-or-state="state" 
          city="a city" 
          zip-code="12345"/>
</storage-info>

<!-- levels: easy, medium, high. extrem -->
<!-- type: downhill (dh.gif), pointtopoint (tourab.gfi), round (tourr.gif), trail (trail.gif)-->
<general fitness-level="easy" tech-level="medium" type="round" duration="01:00hrs">
   <name>The Name Of The Tour</name>
   <distance overwrite="no" unit="km">10</distance>
   <desc>
       Give a short overview here
   </desc>
   <reach>
      <option name="Car">
         Explain how to get to the starting point via car.
      </option>
      <option name="Train">
         Explain how to get to the starting point via train.
      </option>
      <option name="Plane"> 
        Explain how to get to the starting point via plane.
      </option>
   </reach>
   <maps>
      <map>Publisher, Card number 170</map>
   </maps>
   <!-- image of the map -->
   <roadmap image="no-map.png"/>
   <!-- leave this tag as is: The computed profile image will be added here -->
   <profile />
</general>

<crosspoints>
   <!-- first cross point, starting, distance should always be null! -->
   <crosspoint distance="0" elevation="310" direction="north" latitude="000" longitude="000">
      <desc>
         Describe where to go from here.  
      </desc>
      <profile-desc>Alternative text for the profile legend.</profile-desc>
      <!-- If yo have immages add it here 
      <images>
         <image name="drop.jpg"/>
         <image name="loaded-bike2.jpg"/>
      </images>
      -->
   </crosspoint>
   
   <!-- some track info follows -->
   <!-- 
     Pavement types: road, forrest.road, trail
   -->
   <track-info pavement="road">
       <!-- point of interest -->
       <!-- If you got an image use the 'image' attribute
       <poi distance="000" image="loaded-bike.jpg">
       -->
       <poi distance="000">
          Point of interest text.
       </poi>
   </track-info>
   
   <!-- next crosspoint, distance measured to last crosspoint, see that we have
        profile information, pavement will be taken from track-info.
   -->
   <crosspoint distance="500" elevation="315" direction="east" latitude="000" longitude="000">
     <desc>
        Crosspint 2.     
        </desc>
     <!--
     <images>
         <image name="right-turn.jpg"/>
      </images>
      -->
   </crosspoint>
   
   <track-info pavement="road">
       <!-- point of interest -->
       <poi distance="500">
          Another POI.
       </poi>
   </track-info>
   
   <crosspoint distance="500" elevation="320" direction="south" latitude="000" longitude="000">
     <desc>
        Crosspoint 3.
      </desc>
   </crosspoint>
   
   <track-info pavement="forrest.road">
      <eatndrink distance="500" type="restaurant">
          A restaurant.
       </eatndrink>
   </track-info>
   
   <crosspoint distance="800" elevation="330" direction="west" latitude="000" longitude="000">
     <desc>
        Crosspoint 4
      </desc>
      <profile-desc>Crosspoint 4 Profile Text</profile-desc>
   </crosspoint>
   
   <track-info pavement="trail">
      <anecdote distance="All the way">
          Add an anecdote here
      </anecdote>
   </track-info>
   
   <crosspoint distance="500" elevation="430" direction="northeast" latitude="000" longitude="000">
     <desc>
       Crosspoint 5
     </desc>
     <!--
     <images>
         <image name="right-turn.jpg"/>
      </images>
      -->
   </crosspoint>
   
   <track-info pavement="trail">
   </track-info>
   
   <crosspoint distance="200" elevation="600" direction="southeast" latitude="000" longitude="000">
     <desc>
        Crosspoint 6.
     </desc>
   </crosspoint>
   
   <track-info pavement="forrest.road">
   </track-info>
   
   <crosspoint distance="200" elevation="310" direction="southwest" latitude="000" longitude="000">
     <desc>
        Crosspoint 7. Southwest to go, see windrose!.
     </desc>
   </crosspoint>
   
   <track-info pavement="trail">
   </track-info>
   
   <crosspoint distance="300" elevation="600" direction="northwest" latitude="000" longitude="000">
     <desc>
        Crosspoint 8.
     </desc>
   </crosspoint>
   
   <track-info pavement="road">
   </track-info>
   
   <crosspoint distance="200" elevation="310" direction="none" latitude="000" longitude="000">
     <desc>
        Back At Home!
     </desc>
   </crosspoint>

</crosspoints>

</tour-guide>
